networks:
  dev:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - dev

  web:
    image: licaroo/bookworm-web
    restart: always
    volumes:
      - type: volume
        source: static_value
        target: /app/static/
        volume:
          nocopy: false
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - dev

  nginx:
    image: nginx:1.27.2-alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl:/etc/ssl
      - static_value:/var/html/static/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - db
    networks:
      - dev
    restart: always

volumes:
  postgres_data:
  static_value: