# Generated by Django 5.1.2 on 2024-10-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="theme",
            field=models.CharField(
                choices=[
                    ("collaboration", "Сотрудничество"),
                    ("suggestion", "Предложение по улучшению"),
                    ("error", "Ошибка в работе сайта"),
                    ("other", "Другое"),
                ],
                default="suggestion",
                max_length=180,
                verbose_name="Тема",
            ),
        ),
    ]
