# Generated by Django 5.1.2 on 2024-10-28 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedback_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
