# Generated by Django 5.1 on 2024-09-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
