# Generated by Django 5.1 on 2024-09-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ("-created_at",),
                "verbose_name": ("Книга",),
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
