# Generated by Django 5.1 on 2024-09-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
