# Generated by Django 5.1 on 2024-09-21 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_book_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Автор"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.CharField(max_length=400, verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Год публикации"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(
                max_length=300, unique=True, verbose_name="Название"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=400, verbose_name="Текст")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("rating", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commented",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="books.book",
                        verbose_name="Книга",
                    ),
                ),
            ],
        ),
    ]
