# Generated by Django 5.1 on 2024-09-22 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_book_author_alter_book_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="recommended",
            field=models.BooleanField(default=False, verbose_name="Рекомендует"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 - Зря потратил время"),
                    (2, "2 - Не стоит того"),
                    (3, "3 - Средняя, могло быть лучше"),
                    (4, "4 - Хорошая, стоит почитать"),
                    (5, "5 - Отличная, оправдала ожидания"),
                ],
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
