# Generated by Django 5.1 on 2024-09-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_comment_recommended_alter_comment_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
