# Generated by Django 5.1 on 2024-09-22 08:25

from django.db import migrations, models

import books.models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_alter_comment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="recommended",
            field=models.BooleanField(default=False, verbose_name="Рекомендую"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                max_length=1000,
                validators=[books.models.validate_text_length],
                verbose_name="Текст",
            ),
        ),
    ]
