# Generated by Django 5.1 on 2024-10-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_alter_comment_recommended_alter_comment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_edited",
            field=models.BooleanField(default=False, verbose_name="Редактировался"),
        ),
    ]
