# Generated by Django 5.1 on 2024-10-21 03:29

import books.models
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0012_alter_book_created_at_alter_book_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=tinymce.models.HTMLField(
                max_length=1000,
                validators=[books.models.validate_text_length],
                verbose_name="Текст",
            ),
        ),
    ]
