# Generated by Django 5.1 on 2024-10-21 03:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0013_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=tinymce.models.HTMLField(),
        ),
    ]
