# Generated by Django 5.1 on 2024-09-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                blank=True, default="default_avatar.jpg", max_length=200
            ),
        ),
    ]
