name: Main Bookworm Flow

on:
  push:
    branches:
      - main


jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_USER: bookworm_user
          POSTGRES_PASSWORD: bookworm_password
          POSTGRES_DB: bookworm_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8===6.0.0 flake8-isort===6.0.0
          pip install -r ./bookworm/requirements.txt
      - name: Test with flake8 and django tests
        env:
          POSTGRES_USER: bookworm_user
          POSTGRES_PASSWORD: bookworm_password
          POSTGRES_DB: bookworm_db
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DJANGO_SECRET: '23123123secret-key'
          S3_HOST_URL: 'https://b136-3d624fd5227f.selstorage.ru/'
          S3_ACCESS_KEY: 'ddksaklmapdsd2883133'
          S3_SECRET_KEY: 'okdKmdssdms'
          EMAIL_FEEDBACK_RECIPIENT: 'test@example.com'
          EMAIL_HOST_USER: 'your-email@example.com'
          EMAIL_HOST_PASSWORD: 'your-email-password'
          RECAPTCHA_PUBLIC_KEY: 'your-public-key'
          RECAPTCHA_PRIVATE_KEY: 'your-private-key'
        run: |
          python -m flake8 bookworm/
          cd bookworm
          python manage.py test